config/routes.rb
Finances::Application.routes.draw do
  

  

  resources :users

  resources :accounts do
    resources :account_users
  end

  resources :budgets do
    resources :budget_categories
  end

  resources :stores

  

  resources :addresses

  

  resources :articles

  resources :localities

  resources :provinces

  resources :countries

  resources :companies

  resources :brands

  resources :categories

  resources :operations do
    resources :operation_items
  end

  resources :operation_types

  root 'operations#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_many :account_users
	has_many :operations
end

app/models/account_user.rb
class AccountUser < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :locality
	has_many :stores
	has_many :companies
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	belongs_to :brand
	has_many :operation_items
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	belongs_to :company
	has_many :articles
end

app/models/budget.rb
class Budget < ActiveRecord::Base
	has_many :budget_categories
end

app/models/budget_category.rb
class BudgetCategory < ActiveRecord::Base
	belongs_to :budget
	has_many :operation_items
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :articles
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :address
	has_many :brands
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :provinces
end

app/models/locality.rb
class Locality < ActiveRecord::Base
	belongs_to :province
	has_many :addresses
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	has_many :operation_items
	belongs_to :operation_type
	belongs_to :store
	belongs_to :account
end

app/models/operation_item.rb
class OperationItem < ActiveRecord::Base
	belongs_to :operation
	belongs_to :article
	belongs_to :budget_category

	def amount_with_format
		if amount_type == true
		"$" + amount.to_s
		else
		"($" + amount.to_s + ")"
		end
	end


end

app/models/operation_type.rb
class OperationType < ActiveRecord::Base
	has_many :operations

	validates :title, :presence => true
end

app/models/province.rb
class Province < ActiveRecord::Base
	belongs_to :country
	has_many :localities
end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :address
	has_many :operations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :account_users
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  before_action :set_locality, only: [:show, :edit, :update, :destroy]

  # GET /localities
  # GET /localities.json
  def index
    @localities = Locality.all
  end

  # GET /localities/1
  # GET /localities/1.json
  def show
  end

  # GET /localities/new
  def new
    @locality = Locality.new
  end

  # GET /localities/1/edit
  def edit
  end

  # POST /localities
  # POST /localities.json
  def create
    @locality = Locality.new(locality_params)

    respond_to do |format|
      if @locality.save
        format.html { redirect_to :action => :index, notice: 'Locality was successfully created.' }
        format.json { render action: 'show', status: :created, location: @locality }
      else
        format.html { render action: 'new' }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /localities/1
  # PATCH/PUT /localities/1.json
  def update
    respond_to do |format|
      if @locality.update(locality_params)
        format.html { redirect_to :action => :index, notice: 'Locality was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @locality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /localities/1
  # DELETE /localities/1.json
  def destroy
    @locality.destroy
    respond_to do |format|
      format.html { redirect_to localities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locality
      @locality = Locality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locality_params
      params.require(:locality).permit(:province_id, :name, :postal_code)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/localities/_form.html.erb
<%= form_for(@locality) do |f| %>
  <% if @locality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locality.errors.count, "error") %> prohibited this locality from being saved:</h2>

      <ul>
      <% @locality.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :province_id %><br>
    <%= f.number_field :province_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/localities/edit.html.erb
<h1>Editing locality</h1>

<%= render 'form' %>

<%= link_to 'Show', @locality %> |
<%= link_to 'Back', localities_path %>

app/views/localities/index.html.erb
<h1>Listing localities</h1>

<table>
  <thead>
    <tr>
      <th>Province</th>
      <th>Name</th>
      <th>Postal code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @localities.each do |locality| %>
      <tr>
        <td><%= locality.province_id %></td>
        <td><%= locality.name %></td>
        <td><%= locality.postal_code %></td>
        <td><%= link_to 'Show', locality %></td>
        <td><%= link_to 'Edit', edit_locality_path(locality) %></td>
        <td><%= link_to 'Destroy', locality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locality', new_locality_path %>

app/views/localities/new.html.erb
<h1>New locality</h1>

<%= render 'form' %>

<%= link_to 'Back', localities_path %>

app/views/localities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Province:</strong>
  <%= @locality.province_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @locality.name %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @locality.postal_code %>
</p>

<%= link_to 'Edit', edit_locality_path(@locality) %> |
<%= link_to 'Back', localities_path %>