config/routes.rb
Finances::Application.routes.draw do
  

  

  resources :users

  resources :accounts do
    resources :account_users
  end

  resources :budgets do
    resources :budget_categories
  end

  resources :stores

  

  resources :addresses

  

  resources :articles

  resources :localities

  resources :provinces

  resources :countries

  resources :companies

  resources :brands

  resources :categories

  resources :operations do
    resources :operation_items
  end

  resources :operation_types

  root 'operations#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_many :account_users
	has_many :operations
end

app/models/account_user.rb
class AccountUser < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :locality
	has_many :stores
	has_many :companies
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	belongs_to :brand
	has_many :operation_items
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	belongs_to :company
	has_many :articles
end

app/models/budget.rb
class Budget < ActiveRecord::Base
	has_many :budget_categories
end

app/models/budget_category.rb
class BudgetCategory < ActiveRecord::Base
	belongs_to :budget
	has_many :operation_items
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :articles
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :address
	has_many :brands
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :provinces
end

app/models/locality.rb
class Locality < ActiveRecord::Base
	belongs_to :province
	has_many :addresses
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	has_many :operation_items
	belongs_to :operation_type
	belongs_to :store
	belongs_to :account
end

app/models/operation_item.rb
class OperationItem < ActiveRecord::Base
	belongs_to :operation
	belongs_to :article
	belongs_to :budget_category

	def amount_with_format
		if amount_type == true
		"$" + amount.to_s
		else
		"($" + amount.to_s + ")"
		end
	end


end

app/models/operation_type.rb
class OperationType < ActiveRecord::Base
	has_many :operations

	validates :title, :presence => true
end

app/models/province.rb
class Province < ActiveRecord::Base
	belongs_to :country
	has_many :localities
end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :address
	has_many :operations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :account_users
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to :action => :index, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to :action => :index, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:address_id, :name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.number_field :address_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.address_id %></td>
        <td><%= store.name %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @store.address_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>