config/routes.rb
Finances::Application.routes.draw do
  

  

  resources :users

  resources :accounts do
    resources :account_users
  end

  resources :budgets do
    resources :budget_categories
  end

  resources :stores

  

  resources :addresses

  

  resources :articles

  resources :localities

  resources :provinces

  resources :countries

  resources :companies

  resources :brands

  resources :categories

  resources :operations do
    resources :operation_items
  end

  resources :operation_types

  root 'operations#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_many :account_users
	has_many :operations
end

app/models/account_user.rb
class AccountUser < ActiveRecord::Base
  belongs_to :account
  belongs_to :user
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :locality
	has_many :stores
	has_many :companies
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :category
	belongs_to :brand
	has_many :operation_items
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	belongs_to :company
	has_many :articles
end

app/models/budget.rb
class Budget < ActiveRecord::Base
	has_many :budget_categories
end

app/models/budget_category.rb
class BudgetCategory < ActiveRecord::Base
	belongs_to :budget
	has_many :operation_items
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :category
	has_many :categories
	has_many :articles
end

app/models/company.rb
class Company < ActiveRecord::Base
	belongs_to :address
	has_many :brands
end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :provinces
end

app/models/locality.rb
class Locality < ActiveRecord::Base
	belongs_to :province
	has_many :addresses
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	has_many :operation_items
	belongs_to :operation_type
	belongs_to :store
	belongs_to :account
end

app/models/operation_item.rb
class OperationItem < ActiveRecord::Base
	belongs_to :operation
	belongs_to :article
	belongs_to :budget_category

	def amount_with_format
		if amount_type == true
		"$" + amount.to_s
		else
		"($" + amount.to_s + ")"
		end
	end


end

app/models/operation_type.rb
class OperationType < ActiveRecord::Base
	has_many :operations

	validates :title, :presence => true
end

app/models/province.rb
class Province < ActiveRecord::Base
	belongs_to :country
	has_many :localities
end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :address
	has_many :operations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :account_users
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all.limit(2).offset(params[:offset])
    @next_offset = params[:offset].to_i + 2
    @prev_offset = params[:offset].to_i - 2

    @count = Operation.all.count

    @req = request.env['REMOTE_ADDR']
    @request = request.inspect

    respond_to do |format|
      format.html
      format.xml{ render xml: @operations.to_xml }
      format.json{ render json: @operations.to_json }
    end

    

  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to new_operation_item_url(:operation_id => @operation.id)}
        format.json { render action: 'show', status: :created, location: @operation }
      else
        format.html { render action: 'new' }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to :action => :index, notice: 'Operation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:operation_type_id, :store_id, :title, :account_id, :amount)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operation_type_id %><br>
    <%= f.number_field :operation_type_id %>
  </div>
  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.number_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>


<%#=@req %>

<%#=@request %>
<table>
  <thead>
    <tr>
      <th>Operation type</th>
      <th>Store</th>
      <th>Title</th>
      <th>Account</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.operation_type_id %></td>
        <td><%= operation.store_id %></td>
        <td><%= operation.title %></td>
        <td><%= operation.account_id %></td>
        <td><%= operation.amount %></td>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @prev_offset >= 0 %>
  <%= link_to 'Previous', operations_path(:offset => @prev_offset) %>
<% end %>
<% if @count > @next_offset %>
  <%= link_to 'Next', operations_path(:offset => @next_offset) %>
<% end %>
<br>
<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operation type:</strong>
  <%= @operation.operation_type_id %>
</p>

<p>
  <strong>Store:</strong>
  <%= @operation.store_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @operation.title %>
</p>

<p>
  <strong>Account:</strong>
  <%= @operation.account_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @operation.amount %>
</p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>